### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'srcObject')

### ISSUE THREAD

**Issue by AbhinavNaman** [adrianhajdin/project_video_chat#20]
Cannot set properties of undefined (setting 'srcObject')
TypeError: Cannot set properties of undefined (setting 'srcObject')
    at http://localhost:3000/static/js/bundle.js:181:33

**Comment by shivamt2708** [comment]
okk

**Comment by mohan-246** [comment]
Heyy how did you fix it?

**Comment by tusharsircar95** [comment]
_myVideo_ and _userVideo_ references are initialized to null via useRef(). Hence, _myVideo.current_ and _currentVideo.current_ are null, which is why you see the above error.

The solution is to assign a value to this reference which is done [here](https://github.com/adrianhajdin/project_video_chat/blob/b88970719bc4e2482e429d4e7fb4f47dc0762fad/client/src/components/VideoPlayer.jsx#L36).

See more details about setting reference via the _refs_ property [here](https://react.dev/learn/manipulating-the-dom-with-refs).

**Comment by trane7776** [comment]
just delete the part of this
`{stream && () }`
It's because your ref doesn't create before you run a streaming video.

**Comment by RahulKumar9988** [comment]
simple-peer.js?v=b99cf10f:4101 Uncaught TypeError: Cannot read properties of undefined (reading 'call')
at callUser (SocketContext.jsx:53:18)
at onClick (Options.jsx:52:32)

unable to debug this
